from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Protocol, runtime_checkable

from haruka.domain import IncomingMessage

MessageHandler = Callable[[IncomingMessage, object], Awaitable[None]]


@runtime_checkable
class TelegramTransport(Protocol):
    """Minimal contract implemented by MTProto, Bot API, TDLib or test adapters."""

    async def start(self, handler: MessageHandler) -> None: ...
    async def run_forever(self) -> None: ...
    async def close(self) -> None: ...
    async def send_chat_message(self, chat_id: int, text: str, *, reply_to: int | None = None) -> None: ...
    async def load_recent_texts(self, chat_id: int, limit: int = 500) -> list[str]: ...
    async def scan_recent_messages(self, limit_per_chat: int = 5) -> list[IncomingMessage]: ...
    async def known_dialogs(self) -> list[tuple[int, str | None]]: ...
