[tool.black]
extend-exclude = "loaded_modules"
preview = true

[tool.poetry]
name = "haruka"
version = "1.0.0"
description = "Haruka userbot based on Haruka core with migrated custom features"
authors = ["codrago, t.me/codrago"]
license = "GNU AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiofile = "3.8.1"
gitpython = "3.1.27"
meval = "2.5"
aiohttp-jinja2 = "1.5"
aiohttp = ">=3.9,<3.12"
jinja2 = "3.0.3"
requests = "2.27.1"
beautifulsoup4 = ">=4.12,<5"
aiogram = ">=3,<4"
grapheme = "0.6.0"
emoji = "2.1.0"
werkzeug = "2.2.2"
psutil = "5.9.4"
tgcrypto = "1.2.5"
telethon = "1.36.0"
ruamel-yaml = "0.17.21"
rsa = "4.9"
yt-dlp = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
